In [184]:
%matplotlib
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.simplefilter('ignore')
from scipy import stats

c  = 299792458/1.00029
h  = 25000
L  = 100
v  = 1.00029 * c
zc = (c*L)/np.sqrt(v*v - c*c)

Using matplotlib backend: Qt5Agg


## $ z_c \hspace{0.3cm} $ vs $  \hspace{0.3cm}  Brightness $ 

In [220]:
T, Z1, Z2, B1, B2, TH1, TH2 = [], [], [], [], [], [], []
times     = np.linspace(1e-6,1e-4,30,endpoint=True)

for t in times:
    
    z  = h - v*t
    tt = t + np.sqrt(L*L+z*z)/c
       
    # SOLVE QUADRATIC FORMULA AND DIRECTLY PROVIDE THE ROOTS
    z1   = ( (c*c*h - c*c*tt*v) + np.sqrt((c*c*v*v*h*h) - (2*h*tt*c*c*v*v*v) + (L*L*c*c*v*v) + (c*c*tt*tt*v*v*v*v) - (L*L*v*v*v*v)) ) / (c*c - v*v)
    z2   = ( (c*c*h - c*c*tt*v) - np.sqrt((c*c*v*v*h*h) - (2*h*tt*c*c*v*v*v) + (L*L*c*c*v*v) + (c*c*tt*tt*v*v*v*v) - (L*L*v*v*v*v)) ) / (c*c - v*v)
    
    v1   = ( ( (c*c*v*v*(2*tt*v*v - 2*h*v)) / (2*np.sqrt(c*c*v*v*(h*h+L*L+tt*tt*v*v-2*h*tt*v)-(L*L*v**4)   )) ) - (c*c*v) ) / (c*c - v*v)
    v2   = (-( (c*c*v*v*(2*tt*v*v - 2*h*v)) / (2*np.sqrt(c*c*v*v*(h*h+L*L+tt*tt*v*v-2*h*tt*v)-(L*L*v**4)   )) ) - (c*c*v) ) / (c*c - v*v)
    
    theta1 = np.arctan(z1/L)
    theta2 = np.arctan(z2/L)
    
    v1t  = v1 * np.cos(theta1)
    v2t  = v2 * np.cos(theta2)
    
    omg1 = v1t / np.sqrt(L*L + z1*z1)
    omg2 = v2t / np.sqrt(L*L + z2*z2)
    
    b1   = abs(omg1 / (L*L + z1*z1) )
    b2   = abs(omg2 / (L*L + z2*z2) )      
    
    if (z1>25000) or (z1<0) or (z2>25000) or (z2<0):
        pass
    else:
        T .append(tt)
        Z1.append(z1)
        Z2.append(z2)
        B1.append(b1)
        B2.append(b2)
        TH1.append(np.rad2deg(theta1))
        TH2.append(np.rad2deg(theta2))
        
T  = np.array(T )
Z1 = np.array(Z1)
Z2 = np.array(Z2)
B1 = np.array(B1)
B2 = np.array(B2)
TH1 = np.array(TH1)
TH2 = np.array(TH2)

T.shape[0], Z1.shape[0], Z2.shape[0], B1.shape[0], B2.shape[0]

def ground_brightness(tt, z1=0, theta=0):
    v1   = ( ( (c*c*v*v*(2*tt*v*v - 2*h*v)) / (2*np.sqrt(c*c*v*v*(h*h+L*L+tt*tt*v*v-2*h*tt*v)-(L*L*v**4)   )) ) - (c*c*v) ) / (c*c - v*v)
    v1t  = v1 * np.cos(theta)
    omg1 = v1t / np.sqrt(L*L + z1*z1)
    bg   = abs(omg1 / (L*L + z1*z1) )
    return bg

Bg = ground_brightness(((h/v)+(L/c)), 0, 0)
T

(24, 24, 24, 24, 24)

array([8.34155926e-05, 8.34146318e-05, 8.34136736e-05, 8.34127185e-05,
       8.34117668e-05, 8.34108191e-05, 8.34098761e-05, 8.34089385e-05,
       8.34080075e-05, 8.34070843e-05, 8.34061704e-05, 8.34052682e-05,
       8.34043805e-05, 8.34035112e-05, 8.34026656e-05, 8.34018517e-05,
       8.34010810e-05, 8.34003718e-05, 8.33997542e-05, 8.33992816e-05,
       8.33990591e-05, 8.33993261e-05, 8.34007693e-05, 8.34064861e-05])

In [212]:
B1 = B1/Bg
B2 = B2/Bg

In [221]:
args = np.argsort(T)
T = T[args]
B1 = B1[args]
B2 = B2[args]
TH1 = TH1[args]
TH2 = TH2[args]

In [235]:
TH1.round(3)

array([88.594, 88.254, 88.215, 87.914, 87.574, 87.379, 87.234, 86.894,
       86.555, 86.215, 85.875, 85.536, 85.196, 85.079, 84.857, 84.517,
       84.178, 83.839, 83.5  , 83.161, 82.822, 82.484, 82.145, 81.807])

In [231]:
T*1e+9

array([83399.05911862, 83399.28157848, 83399.32607594, 83399.75420724,
       83400.37184052, 83400.7692985 , 83401.08101205, 83401.85166339,
       83402.66559783, 83403.51115478, 83404.38051699, 83405.26824763,
       83406.17044835, 83406.48611837, 83407.08425103, 83408.00749855,
       83408.93853734, 83409.87607856, 83410.81910275, 83411.766793  ,
       83412.71848699, 83413.67364209, 83414.6318095 , 83415.59261478])

In [236]:
TH2.round(3)

array([88.646, 88.91 , 88.934, 89.088, 89.215, 89.274, 89.312, 89.387,
       89.448, 89.497, 89.539, 89.574, 89.604, 89.613, 89.63 , 89.653,
       89.673, 89.691, 89.707, 89.722, 89.735, 89.747, 89.758, 89.768])

In [238]:
s = 2
t = int(s/2)
tx = T[:s]#.reshape(-1,1)
bx = np.concatenate((B1 [:t], B2 [:t]))#.reshape(-1,1)
ax = np.concatenate((TH1[:t], TH2[:t]))#.reshape(-1,1)
tx*1e+9
ax

array([83399.05911862, 83399.28157848])

array([88.59384625, 88.64625935])

In [239]:
s = 4
t = int(s/2)
tx = T[:s]#.reshape(-1,1)
bx = np.concatenate((B1 [:t], B2 [:t]))#.reshape(-1,1)
ax = np.concatenate((TH1[:t], TH2[:t]))#.reshape(-1,1)
tx*1e+9
ax

array([83399.05911862, 83399.28157848, 83399.32607594, 83399.75420724])

array([88.59384625, 88.25389612, 88.64625935, 88.90983184])

In [226]:
points = np.arange(2,100,4)
for i in points:
    plt.figure()
    s = i
    t = int(s/2)
    
    tx = T[:s]#.reshape(-1,1)
    bx = np.concatenate((B1 [:t], B2 [:t]))#.reshape(-1,1)
    ax = np.concatenate((TH1[:t], TH2[:t]))#.reshape(-1,1)
    print(tx)

    import matplotlib
    import matplotlib.pyplot as plt
    import random

    x         = list(tx)
    y         = list(ax)
    z         = list(bx)
    cmap      = matplotlib.cm.get_cmap('viridis')
    normalize = matplotlib.colors.Normalize(0,10)#vmin=min(z), vmax=max(z))
    colors    = [cmap(normalize(value)) for value in z]

    fig, ax   = plt.subplots(figsize=(10,10))
    plt.scatter(x, y, c=colors, s=50);
    plt.xlabel('Time');
    plt.ylabel('Angle');
    plt.title('First {} Time Points'.format(s));
    plt.xlim(0.000083390,0.000083425);
    plt.ylim(85.4,89.6)
    cax, _ = matplotlib.colorbar.make_axes(ax);
    cbar = matplotlib.colorbar.ColorbarBase(cax, cmap=cmap, norm=normalize, label='Relative Brightness');
    plt.savefig('/home/kaushal/Videos/{}.png'.format(i));

<Figure size 640x480 with 0 Axes>

[8.33990591e-05 8.33992816e-05]


Text(0.5, 0, 'Time')

Text(0, 0.5, 'Angle')

Text(0.5, 1.0, 'First 2 Time Points')

(8.339e-05, 8.3425e-05)

(85.4, 89.6)

<Figure size 640x480 with 0 Axes>

[8.33990591e-05 8.33992816e-05 8.33993261e-05 8.33997542e-05]


Text(0.5, 0, 'Time')

Text(0, 0.5, 'Angle')

Text(0.5, 1.0, 'First 4 Time Points')

(8.339e-05, 8.3425e-05)

(85.4, 89.6)

<Figure size 640x480 with 0 Axes>

[8.33990591e-05 8.33992816e-05 8.33993261e-05 8.33997542e-05
 8.34003718e-05 8.34007693e-05]


Text(0.5, 0, 'Time')

Text(0, 0.5, 'Angle')

Text(0.5, 1.0, 'First 6 Time Points')

(8.339e-05, 8.3425e-05)

(85.4, 89.6)

<Figure size 640x480 with 0 Axes>

[8.33990591e-05 8.33992816e-05 8.33993261e-05 8.33997542e-05
 8.34003718e-05 8.34007693e-05 8.34010810e-05 8.34018517e-05]


Text(0.5, 0, 'Time')

Text(0, 0.5, 'Angle')

Text(0.5, 1.0, 'First 8 Time Points')

(8.339e-05, 8.3425e-05)

(85.4, 89.6)

<Figure size 640x480 with 0 Axes>

[8.33990591e-05 8.33992816e-05 8.33993261e-05 8.33997542e-05
 8.34003718e-05 8.34007693e-05 8.34010810e-05 8.34018517e-05
 8.34026656e-05 8.34035112e-05]


Text(0.5, 0, 'Time')

Text(0, 0.5, 'Angle')

Text(0.5, 1.0, 'First 10 Time Points')

(8.339e-05, 8.3425e-05)

(85.4, 89.6)

<Figure size 640x480 with 0 Axes>

[8.33990591e-05 8.33992816e-05 8.33993261e-05 8.33997542e-05
 8.34003718e-05 8.34007693e-05 8.34010810e-05 8.34018517e-05
 8.34026656e-05 8.34035112e-05 8.34043805e-05 8.34052682e-05]


Text(0.5, 0, 'Time')

Text(0, 0.5, 'Angle')

Text(0.5, 1.0, 'First 12 Time Points')

(8.339e-05, 8.3425e-05)

(85.4, 89.6)

<Figure size 640x480 with 0 Axes>

[8.33990591e-05 8.33992816e-05 8.33993261e-05 8.33997542e-05
 8.34003718e-05 8.34007693e-05 8.34010810e-05 8.34018517e-05
 8.34026656e-05 8.34035112e-05 8.34043805e-05 8.34052682e-05
 8.34061704e-05 8.34064861e-05]


Text(0.5, 0, 'Time')

Text(0, 0.5, 'Angle')

Text(0.5, 1.0, 'First 14 Time Points')

(8.339e-05, 8.3425e-05)

(85.4, 89.6)

<Figure size 640x480 with 0 Axes>

[8.33990591e-05 8.33992816e-05 8.33993261e-05 8.33997542e-05
 8.34003718e-05 8.34007693e-05 8.34010810e-05 8.34018517e-05
 8.34026656e-05 8.34035112e-05 8.34043805e-05 8.34052682e-05
 8.34061704e-05 8.34064861e-05 8.34070843e-05 8.34080075e-05]


Text(0.5, 0, 'Time')

Text(0, 0.5, 'Angle')

Text(0.5, 1.0, 'First 16 Time Points')

(8.339e-05, 8.3425e-05)

(85.4, 89.6)

<Figure size 640x480 with 0 Axes>

[8.33990591e-05 8.33992816e-05 8.33993261e-05 8.33997542e-05
 8.34003718e-05 8.34007693e-05 8.34010810e-05 8.34018517e-05
 8.34026656e-05 8.34035112e-05 8.34043805e-05 8.34052682e-05
 8.34061704e-05 8.34064861e-05 8.34070843e-05 8.34080075e-05
 8.34089385e-05 8.34098761e-05]


Text(0.5, 0, 'Time')

Text(0, 0.5, 'Angle')

Text(0.5, 1.0, 'First 18 Time Points')

(8.339e-05, 8.3425e-05)

(85.4, 89.6)

<Figure size 640x480 with 0 Axes>

[8.33990591e-05 8.33992816e-05 8.33993261e-05 8.33997542e-05
 8.34003718e-05 8.34007693e-05 8.34010810e-05 8.34018517e-05
 8.34026656e-05 8.34035112e-05 8.34043805e-05 8.34052682e-05
 8.34061704e-05 8.34064861e-05 8.34070843e-05 8.34080075e-05
 8.34089385e-05 8.34098761e-05 8.34108191e-05 8.34117668e-05]


Text(0.5, 0, 'Time')

Text(0, 0.5, 'Angle')

Text(0.5, 1.0, 'First 20 Time Points')

(8.339e-05, 8.3425e-05)

(85.4, 89.6)

<Figure size 640x480 with 0 Axes>

[8.33990591e-05 8.33992816e-05 8.33993261e-05 8.33997542e-05
 8.34003718e-05 8.34007693e-05 8.34010810e-05 8.34018517e-05
 8.34026656e-05 8.34035112e-05 8.34043805e-05 8.34052682e-05
 8.34061704e-05 8.34064861e-05 8.34070843e-05 8.34080075e-05
 8.34089385e-05 8.34098761e-05 8.34108191e-05 8.34117668e-05
 8.34127185e-05 8.34136736e-05]


Text(0.5, 0, 'Time')

Text(0, 0.5, 'Angle')

Text(0.5, 1.0, 'First 22 Time Points')

(8.339e-05, 8.3425e-05)

(85.4, 89.6)

<Figure size 640x480 with 0 Axes>

[8.33990591e-05 8.33992816e-05 8.33993261e-05 8.33997542e-05
 8.34003718e-05 8.34007693e-05 8.34010810e-05 8.34018517e-05
 8.34026656e-05 8.34035112e-05 8.34043805e-05 8.34052682e-05
 8.34061704e-05 8.34064861e-05 8.34070843e-05 8.34080075e-05
 8.34089385e-05 8.34098761e-05 8.34108191e-05 8.34117668e-05
 8.34127185e-05 8.34136736e-05 8.34146318e-05 8.34155926e-05]


Text(0.5, 0, 'Time')

Text(0, 0.5, 'Angle')

Text(0.5, 1.0, 'First 24 Time Points')

(8.339e-05, 8.3425e-05)

(85.4, 89.6)

In [217]:
tx.shape, bx.shape, ax.shape
sns.jointplot(bx,ax,kind='hex').set_axis_labels("Relative Brightness","Angle")

AttributeError: 'AxesSubplot' object has no attribute 'shape'

In [124]:
g = sns.jointplot(bx, ax, kind="hex")
g.ax_marg_x.set_axis_off()
g.ax_marg_y.set_axis_off()
g.set_axis_labels("Relative Brightness","Angle")

In [107]:
tx, bx, ax

g = sns.JointGrid(ax, bx, ratio=100)
g.plot_marginals(False)
g.plot_joint(sns.scatterplot)
g.ax_marg_x.set_axis_off()
g.ax_marg_y.set_axis_off()
g.set_axis_labels("Angle", "Relative Brightness")

(array([[8.34155926e-05],
        [8.34155912e-05],
        [8.34155898e-05],
        ...,
        [8.34128179e-05],
        [8.34128165e-05],
        [8.34128151e-05]]), array([[4.15802761e-02],
        [4.15754997e-02],
        [4.15707231e-02],
        ...,
        [1.22520578e-06],
        [1.22552421e-06],
        [1.22584274e-06]]), array([[81.80688396],
        [81.80737464],
        [81.80786531],
        ...,
        [89.75325619],
        [89.75324042],
        [89.75322464]]))

TypeError: 'bool' object is not callable

In [69]:
sns.jointplot(ax,bx,s=100).set_axis_labels("Angle", "Relative Brightness")
plt.title(r'$\delta t$')

Text(0.5, 1.0, '$\\delta t$')

In [ ]:
b1   = np.concatenate((B1,B2))
a1   = np.concatenate((TH1,TH2))
args = np.argsort(a1)
a2   = a1[args]
b2   = b1[args]
sns.jointplot(ax,bx,s=100).set_axis_labels("Angle", "Relative Brightness")#

In [ ]:
a2 = a2.reshape(-1,1)
b2 = b2.reshape(-1,1)

In [ ]:
sns.jointplot(a2, b2, kind="hex")

In [ ]:
import seaborn as sns
#sns.heatmap(np.random.random((100,1)))
from matplotlib import transforms
tr = transforms.Affine2D().rotate_deg(90)
#B = np.array([1,2,3,4,5,4,3,4,5,100])
sns.heatmap(B.reshape(1,B.shape[0]), square=True)
plt.show()