In [3]:
%matplotlib
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import matplotlib
import matplotlib.pyplot as plt
import random
warnings.simplefilter('ignore')
from scipy import stats

c  = 299792458/1.00029
h  = 25000
L  = 100
v  = 1.00029 * c
zc = (c*L)/np.sqrt(v*v - c*c)

Using matplotlib backend: Qt5Agg


## $ z_c \hspace{0.3cm} $ vs $  \hspace{0.3cm}  Brightness $ 

In [45]:
T, Z1, Z2, B1, B2, TH1, TH2 = [], [], [], [], [], [], []
times     = np.linspace(1e-6,1e-4,50,endpoint=True)

for t in times:
    
    z  = h - v*t
    tt = t + np.sqrt(L*L+z*z)/c
       
    # SOLVE QUADRATIC FORMULA AND DIRECTLY PROVIDE THE ROOTS
    z1   = ( (c*c*h - c*c*tt*v) + np.sqrt((c*c*v*v*h*h) - (2*h*tt*c*c*v*v*v) + (L*L*c*c*v*v) + (c*c*tt*tt*v*v*v*v) - (L*L*v*v*v*v)) ) / (c*c - v*v)
    z2   = ( (c*c*h - c*c*tt*v) - np.sqrt((c*c*v*v*h*h) - (2*h*tt*c*c*v*v*v) + (L*L*c*c*v*v) + (c*c*tt*tt*v*v*v*v) - (L*L*v*v*v*v)) ) / (c*c - v*v)
    
    v1   = ( ( (c*c*v*v*(2*tt*v*v - 2*h*v)) / (2*np.sqrt(c*c*v*v*(h*h+L*L+tt*tt*v*v-2*h*tt*v)-(L*L*v**4)   )) ) - (c*c*v) ) / (c*c - v*v)
    v2   = (-( (c*c*v*v*(2*tt*v*v - 2*h*v)) / (2*np.sqrt(c*c*v*v*(h*h+L*L+tt*tt*v*v-2*h*tt*v)-(L*L*v**4)   )) ) - (c*c*v) ) / (c*c - v*v)
    
    theta1 = np.arctan(z1/L)
    theta2 = np.arctan(z2/L)
    
    v1t  = v1 * np.cos(theta1)
    v2t  = v2 * np.cos(theta2)
    
    omg1 = v1t / np.sqrt(L*L + z1*z1)
    omg2 = v2t / np.sqrt(L*L + z2*z2)
    
    b1   = abs(omg1 / (L*L + z1*z1) )
    b2   = abs(omg2 / (L*L + z2*z2) )      
    
    if (z1>25000) or (z1<0) or (z2>25000) or (z2<0):
        pass
    else:
        T .append(tt)
        Z1.append(z1)
        Z2.append(z2)
        B1.append(b1)
        B2.append(b2)
        TH1.append(np.rad2deg(theta1))
        TH2.append(np.rad2deg(theta2))
        
T  = np.array(T )
Z1 = np.array(Z1)
Z2 = np.array(Z2)
B1 = np.array(B1)
B2 = np.array(B2)
TH1 = np.array(TH1)
TH2 = np.array(TH2)

T.shape[0], Z1.shape[0], Z2.shape[0], B1.shape[0], B2.shape[0]

def ground_brightness(tt, z1=0, theta=0):
    v1   = ( ( (c*c*v*v*(2*tt*v*v - 2*h*v)) / (2*np.sqrt(c*c*v*v*(h*h+L*L+tt*tt*v*v-2*h*tt*v)-(L*L*v**4)   )) ) - (c*c*v) ) / (c*c - v*v)
    v1t  = v1 * np.cos(theta)
    omg1 = v1t / np.sqrt(L*L + z1*z1)
    bg   = abs(omg1 / (L*L + z1*z1) )
    return bg

Bg = ground_brightness(((h/v)+(L/c)), 0, 0)

(40, 40, 40, 40, 40)

In [46]:
B1 = B1/Bg
B2 = B2/Bg

In [47]:
%matplotlib
args = np.argsort(T)
T = T[args]
B1 = B1[args]
B2 = B2[args]
TH1 = TH1[args]
TH2 = TH2[args]

Using matplotlib backend: Qt5Agg


In [64]:
points = np.arange(2,41,2)
for i in points:
    
    plt.figure()
    s = i
    t = int(s/2)
    
    tx  = T[:s]
    
    bx1 = np.array(B1[:t]).reshape(-1,1)
    bx2 = np.array(B2[:t]).reshape(-1,1)
    bx  = np.concatenate((bx1,bx2),axis=1).flatten()

    ax1 = np.array(TH1[:t]).reshape(-1,1)
    ax2 = np.array(TH2[:t]).reshape(-1,1)
    ax  = np.concatenate((ax1,ax2),axis=1).flatten()

    x         = list(tx)
    y         = list(ax)
    z         = list(bx)

    cmap      = matplotlib.cm.get_cmap('viridis')
    normalize = matplotlib.colors.Normalize(vmin=0, vmax=0.0225)
    colors    = [cmap(normalize(value)) for value in z]

    fig, ax   = plt.subplots(figsize=(10,10));
    plt.scatter([i*1e+9 for i in x], y, c=colors, s=400, marker='H',alpha=0.8)
    plt.xlabel(r'$t_{total} (ns)$', fontsize=26);
    plt.ylabel(r'$\theta\;(Degrees)$',fontsize=24);
    #plt.title('First {} Time Points'.format(s));
    plt.xlim(83397,83416.4);
    plt.ylim(85.2,89.7);#89.5
    plt.tick_params(axis='both', which='major', labelsize=20, direction='in')
    cax, _ = matplotlib.colorbar.make_axes(ax);
    cbar = matplotlib.colorbar.ColorbarBase(cax, cmap=cmap, norm=normalize, label='Relative Brightness');
    plt.savefig('/home/kaushal/Music/{}.png'.format(i));

<Figure size 640x480 with 0 Axes>

Text(0.5, 0, '$t_{total} (ns)$')

Text(0, 0.5, '$\\theta\\;(Degrees)$')

(83397, 83416.4)

(85.2, 89.7)

<Figure size 640x480 with 0 Axes>

Text(0.5, 0, '$t_{total} (ns)$')

Text(0, 0.5, '$\\theta\\;(Degrees)$')

(83397, 83416.4)

(85.2, 89.7)

<Figure size 640x480 with 0 Axes>

Text(0.5, 0, '$t_{total} (ns)$')

Text(0, 0.5, '$\\theta\\;(Degrees)$')

(83397, 83416.4)

(85.2, 89.7)

<Figure size 640x480 with 0 Axes>

Text(0.5, 0, '$t_{total} (ns)$')

Text(0, 0.5, '$\\theta\\;(Degrees)$')

(83397, 83416.4)

(85.2, 89.7)

<Figure size 640x480 with 0 Axes>

Text(0.5, 0, '$t_{total} (ns)$')

Text(0, 0.5, '$\\theta\\;(Degrees)$')

(83397, 83416.4)

(85.2, 89.7)

<Figure size 640x480 with 0 Axes>

Text(0.5, 0, '$t_{total} (ns)$')

Text(0, 0.5, '$\\theta\\;(Degrees)$')

(83397, 83416.4)

(85.2, 89.7)

<Figure size 640x480 with 0 Axes>

Text(0.5, 0, '$t_{total} (ns)$')

Text(0, 0.5, '$\\theta\\;(Degrees)$')

(83397, 83416.4)

(85.2, 89.7)

<Figure size 640x480 with 0 Axes>

Text(0.5, 0, '$t_{total} (ns)$')

Text(0, 0.5, '$\\theta\\;(Degrees)$')

(83397, 83416.4)

(85.2, 89.7)

<Figure size 640x480 with 0 Axes>

Text(0.5, 0, '$t_{total} (ns)$')

Text(0, 0.5, '$\\theta\\;(Degrees)$')

(83397, 83416.4)

(85.2, 89.7)

<Figure size 640x480 with 0 Axes>

Text(0.5, 0, '$t_{total} (ns)$')

Text(0, 0.5, '$\\theta\\;(Degrees)$')

(83397, 83416.4)

(85.2, 89.7)

<Figure size 640x480 with 0 Axes>

Text(0.5, 0, '$t_{total} (ns)$')

Text(0, 0.5, '$\\theta\\;(Degrees)$')

(83397, 83416.4)

(85.2, 89.7)

<Figure size 640x480 with 0 Axes>

Text(0.5, 0, '$t_{total} (ns)$')

Text(0, 0.5, '$\\theta\\;(Degrees)$')

(83397, 83416.4)

(85.2, 89.7)

<Figure size 640x480 with 0 Axes>

Text(0.5, 0, '$t_{total} (ns)$')

Text(0, 0.5, '$\\theta\\;(Degrees)$')

(83397, 83416.4)

(85.2, 89.7)

<Figure size 640x480 with 0 Axes>

Text(0.5, 0, '$t_{total} (ns)$')

Text(0, 0.5, '$\\theta\\;(Degrees)$')

(83397, 83416.4)

(85.2, 89.7)

<Figure size 640x480 with 0 Axes>

Text(0.5, 0, '$t_{total} (ns)$')

Text(0, 0.5, '$\\theta\\;(Degrees)$')

(83397, 83416.4)

(85.2, 89.7)

<Figure size 640x480 with 0 Axes>

Text(0.5, 0, '$t_{total} (ns)$')

Text(0, 0.5, '$\\theta\\;(Degrees)$')

(83397, 83416.4)

(85.2, 89.7)

<Figure size 640x480 with 0 Axes>

Text(0.5, 0, '$t_{total} (ns)$')

Text(0, 0.5, '$\\theta\\;(Degrees)$')

(83397, 83416.4)

(85.2, 89.7)

<Figure size 640x480 with 0 Axes>

Text(0.5, 0, '$t_{total} (ns)$')

Text(0, 0.5, '$\\theta\\;(Degrees)$')

(83397, 83416.4)

(85.2, 89.7)

<Figure size 640x480 with 0 Axes>

Text(0.5, 0, '$t_{total} (ns)$')

Text(0, 0.5, '$\\theta\\;(Degrees)$')

(83397, 83416.4)

(85.2, 89.7)

<Figure size 640x480 with 0 Axes>

Text(0.5, 0, '$t_{total} (ns)$')

Text(0, 0.5, '$\\theta\\;(Degrees)$')

(83397, 83416.4)

(85.2, 89.7)

In [239]:
s = 4
t = int(s/2)
tx = T[:s]#.reshape(-1,1)
bx = np.concatenate((B1 [:t], B2 [:t]))#.reshape(-1,1)
ax = np.concatenate((TH1[:t], TH2[:t]))#.reshape(-1,1)
tx*1e+9
ax

array([83399.05911862, 83399.28157848, 83399.32607594, 83399.75420724])

array([88.59384625, 88.25389612, 88.64625935, 88.90983184])

In [217]:
tx.shape, bx.shape, ax.shape
sns.jointplot(bx,ax,kind='hex').set_axis_labels("Relative Brightness","Angle")

AttributeError: 'AxesSubplot' object has no attribute 'shape'

In [124]:
g = sns.jointplot(bx, ax, kind="hex")
g.ax_marg_x.set_axis_off()
g.ax_marg_y.set_axis_off()
g.set_axis_labels("Relative Brightness","Angle")

In [107]:
tx, bx, ax

g = sns.JointGrid(ax, bx, ratio=100)
g.plot_marginals(False)
g.plot_joint(sns.scatterplot)
g.ax_marg_x.set_axis_off()
g.ax_marg_y.set_axis_off()
g.set_axis_labels("Angle", "Relative Brightness")

(array([[8.34155926e-05],
        [8.34155912e-05],
        [8.34155898e-05],
        ...,
        [8.34128179e-05],
        [8.34128165e-05],
        [8.34128151e-05]]), array([[4.15802761e-02],
        [4.15754997e-02],
        [4.15707231e-02],
        ...,
        [1.22520578e-06],
        [1.22552421e-06],
        [1.22584274e-06]]), array([[81.80688396],
        [81.80737464],
        [81.80786531],
        ...,
        [89.75325619],
        [89.75324042],
        [89.75322464]]))

TypeError: 'bool' object is not callable

In [69]:
sns.jointplot(ax,bx,s=100).set_axis_labels("Angle", "Relative Brightness")
plt.title(r'$\delta t$')

Text(0.5, 1.0, '$\\delta t$')

In [ ]:
b1   = np.concatenate((B1,B2))
a1   = np.concatenate((TH1,TH2))
args = np.argsort(a1)
a2   = a1[args]
b2   = b1[args]
sns.jointplot(ax,bx,s=100).set_axis_labels("Angle", "Relative Brightness")#

In [ ]:
a2 = a2.reshape(-1,1)
b2 = b2.reshape(-1,1)

In [ ]:
sns.jointplot(a2, b2, kind="hex")

In [ ]:
import seaborn as sns
#sns.heatmap(np.random.random((100,1)))
from matplotlib import transforms
tr = transforms.Affine2D().rotate_deg(90)
#B = np.array([1,2,3,4,5,4,3,4,5,100])
sns.heatmap(B.reshape(1,B.shape[0]), square=True)
plt.show()